name: Playwright Automation Tests with Test Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      ENV: prod   # Sets environment variable used in the script
      BASE_URL: ${{ secrets.BASE_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      VALID_USERNAME: ${{ secrets.VALID_USERNAME }}
      VALID_PASSWORD: ${{ secrets.VALID_PASSWORD }}
      INVALID_USERNAME: ${{ secrets.INVALID_USERNAME }}
      INVALID_PASSWORD: ${{ secrets.INVALID_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Allure CLI v2
        run: npm install -D allure-commandline@2.20.1

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Test Cases with Tag - @e2e
        run: npm run github.run.test.ag:e2e.prod:chrome:allure

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ./allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./allure-report
          publish_branch: gh-pages

    